/*
2026 Winter Games Day 1: Opening Day
Today marks the start of the 2026 Winter Games. The next 17 days will bring you coding challenges inspired by them.

For the first one, you are given a two-letter country code and need to return the flag emoji for that country.

Use this list:
*/

function getFlag(code) {
  switch(code) {
    case "AL":
      return "🇦🇱";
    case "AD":
      return "🇦🇩";
    case "AR":
      return "🇦🇷";
    case "AM":
      return "🇦🇲";
    case "AU":
      return "🇦🇺";
    case "AT":
      return "🇦🇹";
    case "AZ":
      return "🇦🇿";
    case "BE":
      return "🇧🇪";
    case "BJ":
      return "🇧🇯";
    case "BO":
      return "🇧🇴";
    case "BA":
      return "🇧🇦";
    case "BR":
      return "🇧🇷";
    case "BG":
      return "🇧🇬";
    case "CA":
      return "🇨🇦";
    case "CL":
      return "🇨🇱";
    case "CN":
      return "🇨🇳";
    case "CO":
      return "🇨🇴";
    case "HR":
      return "🇭🇷";
    case "CY":
      return "🇨🇾";
    case "CZ":
      return "🇨🇿";
    case "DK":
      return "🇩🇰";
    case "EC":
      return "🇪🇨";
    case "ER":
      return "🇪🇷";
    case "EE":
      return "🇪🇪";
    case "FI":
      return "🇫🇮";
    case "FR":
      return "🇫🇷";
    case "GE":
      return "🇬🇪";
    case "DE":
      return "🇩🇪";
    case "GB":
      return "🇬🇧";
    case "GR":
      return "🇬🇷";
    case "GW":
      return "🇬🇼";
    case "HT":
      return "🇭🇹";
    case "HK":
      return "🇭🇰";
    case "HU":
      return "🇭🇺";
    case "IS":
      return "🇮🇸";
    case "IN":
      return "🇮🇳";
    case "IR":
      return "🇮🇷";
    case "IE":
      return "🇮🇪";
    case "IL":
      return "🇮🇱";
    case "IT":
      return "🇮🇹";
    case "JM":
      return "🇯🇲";
    case "JP":
      return "🇯🇵";
    case "KZ":
      return "🇰🇿";
    case "KE":
      return "🇰🇪";
    case "XK":
      return "🇽🇰";
    case "KG":
      return "🇰🇬";
    case "LV":
      return "🇱🇻";
    case "LB":
      return "🇱🇧";
    case "LI":
      return "🇱🇮";
    case "LT":
      return "🇱🇹";
    case "LU":
      return "🇱🇺";
    case "MG":
      return "🇲🇬";
    case "MY":
      return "🇲🇾";
    case "MT":
      return "🇲🇹";
    case "MX":
      return "🇲🇽";
    case "MD":
      return "🇲🇩";
    case "MC":
      return "🇲🇨";
    case "MN":
      return "🇲🇳";
    case "ME":
      return "🇲🇪";
    case "MA":
      return "🇲🇦";
    case "NL":
      return "🇳🇱";
    case "NZ":
      return "🇳🇿";
    case "NG":
      return "🇳🇬";
    case "MK":
      return "🇲🇰";
    case "NO":
      return "🇳🇴";
    case "PK":
      return "🇵🇰";
    case "PH":
      return "🇵🇭";
    case "PL":
      return "🇵🇱";
    case "PT":
      return "🇵🇹";
    case "PR":
      return "🇵🇷";
    case "RO":
      return "🇷🇴";
    case "SM":
      return "🇸🇲";
    case "SA":
      return "🇸🇦";
    case "RS":
      return "🇷🇸";
    case "SG":
      return "🇸🇬";
    case "SK":
      return "🇸🇰";
    case "SI":
      return "🇸🇮";
    case "ZA":
      return "🇿🇦";
    case "KR":
      return "🇰🇷";
    case "ES":
      return "🇪🇸";
    case "SE":
      return "🇸🇪";
    case "CH":
      return "🇨🇭";
    case "TH":
      return "🇹🇭";
    case "TT":
      return "🇹🇹";
    case "TR":
      return "🇹🇷";
    case "UA":
      return "🇺🇦";
    case "AE":
      return "🇦🇪";
    case "US":
      return "🇺🇸";
    case "UY":
      return "🇺🇾";
    case "UZ":
      return "🇺🇿";
    case "VE":
      return "🇻🇪";
    default:
      return code; // Retourne le code si non trouvé
  }
}